### ISSUE TITLE
I didn't find the paper

### ISSUE THREAD

**Issue by willard-yuan** [wangmaoCS/Fusion_RMAC#1]
Hi @wangmaoCS I'm interested in your work, but I didn't find the paper "Fusing Global and Local Deep Representation for Effective Object Retrieval" in internet. Would you like to send me the paper?

**Comment by willard-yuan** [comment]
I have read the code and understood it.

**Comment by wangmaoCS** [comment]
I'm sorry for the late reply.
My paper is submitted to a conference hold in China and under review, if you need the paper, I can send to you.
Could you give men your e-mail address?






在 2017-05-26 08:32:48，"Yong Yuan" <notifications@github.com> 写道：


Closed #1.

**Comment by willard-yuan** [comment]
@wangmaoCS I have fully read the code and got understood it. But I would like to read your paper. My email is yongyuanstu at gmail dot com.

Thanks.
